data:
  img_prefix: /videos/rawframes
  train:
    ann_file: /videos/labels/Trimmed/primary_intensity_train.csv
    joint_file: /videos/jointlocs/TrimmedNoConf/primary_intensity_joints_train.json
  val:
    ann_file: /videos/labels/Trimmed/primary_intensity_val.csv
    joint_file: /videos/jointlocs/TrimmedNoConf/primary_intensity_joints_val.json
  test:
    ann_file: /videos/labels/Trimmed/primary_intensity_test.csv
    joint_file: /videos/jointlocs/TrimmedNoConf/primary_intensity_joints_test.json
model:
  classes: 5
  layers: 2
  hidden_size: 64
train_settings:
  batch_size: 32
  epochs: 12
  learning_rate: 0.0005
